### ISSUE TITLE
psycopg2.ProgrammingError: relation "mangaitems" does not exist

### ISSUE THREAD

**Issue by jtara1** [fake-name/MangaCMS#14]
It looks like MangaItems table is never created.

```
j@j-pc ~/_Github-Projects/MangaCMS $ python3 mainScrape.py 
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
Have creds for a domain
Have credentials, installing password manager into urllib handler.
Have cred handler. Building opener using it
Have creds for a domain
Have credentials, installing password manager into urllib handler.
Have cred handler. Building opener using it
Have creds for a domain
Have credentials, installing password manager into urllib handler.
Have cred handler. Building opener using it
Have creds for a domain
Have credentials, installing password manager into urllib handler.
Have cred handler. Building opener using it
Setting up loggers....
done
No feedLoader:  <class 'ScrapePlugins.M.BtBaseManager.Run.Runner'>
No feedLoader:  <class 'ScrapePlugins.M.BuMonitor.Run.Runner'>
No feedLoader:  <class 'ScrapePlugins.M.IrcGrabber.IrcEnqueueRun.Runner'>
No feedLoader:  <class 'ScrapePlugins.M.IrcGrabber.BotRunner.Runner'>
No feedLoader:  <class 'ScrapePlugins.M.MangaBox.Run.Runner'>
No feedLoader:  <class 'ScrapePlugins.M.YoMangaLoader.Run.Runner'>
No feedLoader:  <class 'ScrapePlugins.H.DjMoeLoader.Retag.Runner'>
Tables =  ['logtable', 'schemarev', 'pluginstatus']
Current Database Schema Rev =  9
Tables =  ['logtable', 'schemarev', 'pluginstatus']
Ensuring commit hooks for table-size tracking exist.
Ensuring commit hooks for table-size tracking exist.
Main - CRITICAL - Uncaught exception!
Main - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "mainScrape.py", line 189, in <module>
    go()
  File "mainScrape.py", line 149, in go
    preflight()
  File "mainScrape.py", line 142, in preflight
    schemaUpdater.schemaRevisioner.updateDatabaseSchema()
  File "/home/j/_Github-Projects/MangaCMS/schemaUpdater/schemaRevisioner.py", line 100, in updateDatabaseSchema
    setupTableCountersPostgre(conn)
  File "/home/j/_Github-Projects/MangaCMS/schemaUpdater/rowCountTracker.py", line 3, in setupTableCountersPostgre
    initTableCounts(conn, "mangaitems")
  File "/home/j/_Github-Projects/MangaCMS/schemaUpdater/rowCountTracker.py", line 56, in initTableCounts
    FOR EACH ROW EXECUTE PROCEDURE update_row_counts();'''.format(tableName=table))
psycopg2.ProgrammingError: relation "mangaitems" does not exist

```

**Comment by fake-name** [comment]
Did you run [`firstRun.py`](https://github.com/fake-name/MangaCMS/blob/master/firstRun.py)?


[> Once you have the above complete, you will want to run the bootstrap script firstRun.py to do the database setup. After that, you should be able to run mainScrape without issues.](https://github.com/fake-name/MangaCMS/blob/master/README.md#209)

I should probably add database probing to the startup, but I just haven't bothered, really.

**Comment by jtara1** [comment]
```
j@j-pc ~/_Github-Projects/MangaCMS $ python3 firstRun.py 
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
Traceback (most recent call last):
  File "firstRun.py", line 9, in <module>
    import ScrapePlugins.H.DjMoeLoader.djMoeDbLoader
ImportError: No module named 'ScrapePlugins.H.DjMoeLoader.djMoeDbLoader'
```

Yea I tried that.

I started renaming the imports to what seems correct, but got lost at the `toInit` variable in the firstRun.py file.

My changes to `firstRun.py`:

```


'''
Do the initial database setup, so a functional system can be bootstrapped from an empty database.
'''

import ScrapePlugins.M.BuMonitor.MonitorRun
import ScrapePlugins.M.BuMonitor.ChangeMonitor
import ScrapePlugins.H.DjMoeLoader.DbLoader

import ScrapePlugins.M.BtSeriesFetcher.SeriesEnqueuer
import ScrapePlugins.M.BtLoader.DbLoader


'''
We need one instance of each type of plugin (series, manga, hentai), plus some extra for no particular reason (safety!)

Each plugin is instantiated, and then the plugin database setup method is called.

'''
toInit = [
	ScrapePlugins.M.BuMonitor.MonitorRun.BuWatchMonitor,
	ScrapePlugins.M.BuMonitor.ChangeMonitor.BuDateUpdater,
	ScrapePlugins.H.DjMoeLoader.djMoeDbLoader.DjMoeDbLoader,
	ScrapePlugins.M.BtSeriesFetcher.btSeriesEnqueuer.BtSeriesEnqueuer,
	ScrapePlugins.M.BtLoader.btFeedLoader.BtFeedLoader,
	]


def firstRun():
	for plg in toInit:
		print(plg)
		tmp = plg()
		tmp.checkInitPrimaryDb()

if __name__ == "__main__":
	firstRun()
```

```
j@j-pc ~/_Github-Projects/MangaCMS $ python3 firstRun.py 
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
Traceback (most recent call last):
  File "firstRun.py", line 24, in <module>
    ScrapePlugins.H.DjMoeLoader.djMoeDbLoader.DjMoeDbLoader,
AttributeError: module 'ScrapePlugins.H.DjMoeLoader' has no attribute 'djMoeDbLoader'
```

**Comment by fake-name** [comment]
Oh, whoops, I never updated that after cleaning up the plugin structure. Derp derp derp derp.

**Comment by fake-name** [comment]
Ok, I fixed that issue, and also attached the DB bootstrapping to the normal startup procedure (so hopefully it'll not go bad over time again).

I also updated the readme.
