### ISSUE TITLE
AttributeError: module 'settings' has no attribute 'GRAPHITE_DB_IP'

### ISSUE THREAD

**Issue by jtara1** [fake-name/MangaCMS#16]
Running `firstRun.py`:

```
j@j-pc ~/_Github-Projects/MangaCMS $ python3 firstRun.py 
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
<class 'ScrapePlugins.M.BuMonitor.MonitorRun.BuWatchMonitor'>
Traceback (most recent call last):
  File "firstRun.py", line 37, in <module>
    checkInitTables()
  File "firstRun.py", line 33, in checkInitTables
    tmp = plg()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/MonitorDbBase.py", line 49, in __init__
    super().__init__()
  File "/home/j/_Github-Projects/MangaCMS/DbBase.py", line 101, in __init__
    host = settings.GRAPHITE_DB_IP,
AttributeError: module 'settings' has no attribute 'GRAPHITE_DB_IP'
```

**Comment by fake-name** [comment]
In this case, just stick 127.0.0.1 in settings:

`GRAPHITE_DB_IP = "127.0.0.1"`. 

Basically, at runtime, the instrumentation sprays UDP stats messages at the graphite instance (if present).
