### ISSUE TITLE
psycopg2.ProgrammingError: relation "mangaseries" does not exist

### ISSUE THREAD

**Issue by jtara1** [fake-name/MangaCMS#17]
`firstRun.py` completed successfully,

This is part of the output after running `mainScrape.py`

```
Main.Manga.Bt.Base - INFO - BtBase finished.
Job "callMod (trigger: interval[1:00:00], next run at: 2017-05-29 17:38:09 PDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mainScrape.py", line 66, in callMod
    instance.go()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
    self._go()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/M/BtBaseManager/Run.py", line 18, in _go
    monitor.go()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
    self._go()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/RunBase.py", line 121, in _go
    fl.do_fetch_feeds()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/M/BtSeriesFetcher/SeriesLoader.py", line 133, in do_fetch_feeds
    self.scanForSeries()
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/M/BtSeriesFetcher/SeriesLoader.py", line 89, in scanForSeries
    self.wantedIds = set(self.getBuListItemIds())
  File "/home/j/_Github-Projects/MangaCMS/ScrapePlugins/SeriesRetreivalDbBase.py", line 80, in getBuListItemIds
    cur.execute(query)
psycopg2.ProgrammingError: relation "mangaseries" does not exist
LINE 1: SELECT buId FROM MangaSeries WHERE buList IS NOT NULL;
                         ^
```

**Comment by fake-name** [comment]
I'm not sure how that's happening, as the `SeriesScraperDbBase()` subclasses should default create their required tables upon first instantiation.

**Comment by fake-name** [comment]
Let me bootstrap a test environment tonight, to figure out WTF is going on.

**Comment by jtara1** [comment]
I ran the firstRun.py and the mainScrape.py again for at least 10 minutes, and I haven't ran into this problem.

**Comment by fake-name** [comment]
Yeah, what happened is the batoto scheduling plugin barfed. It won't reoccur until it's next executed, which would be after another hour (intervals are specified in https://github.com/fake-name/MangaCMS/blob/master/activePlugins.py#L71).

You shouldn't need to ever run `firstRun.py` again, due to the changes from https://github.com/fake-name/MangaCMS/commit/d233523404f5fb66656c16b843b92147ca1709ac

**Comment by fake-name** [comment]
Ok, that should rectify the issue, I think. One of the table existence checks wasn't getting commit;ed, so the table was never /actually/ being created. Major derpitude.
