### ISSUE TITLE
Attribute Error 'NoneType'

### ISSUE THREAD

**Issue by samishii23** [fake-name/MangaCMS#21]
While Plugin Main.Manga.Bu.Run is running, I think its at the end of the process... It throws the following errors.

```
Main.Manga.Bu.Watcher.Web - INFO - Fetching content at URL: http://www.mangaupdates.com/mylist.html
Main.Manga.Bu.Watcher.Web - INFO - Request for URL: http://www.mangaupdates.com/mylist.html succeeded at Sun Jan 14 13:28:53 2018 On Attempt 1. Recieving...
Main.Manga.Bu.Watcher.Web - INFO - URL fully retrieved.
Main.Manga.Bu.Watcher.Web - INFO - Compression type = gzip. Content Size compressed = 3.074K. Decompressed = 11.499K. File type: text/html; charset=ISO-8859-1.
Main.Manga.Bu.Run - CRITICAL - Uncaught major exception in plugin!
Main.Manga.Bu.Run - CRITICAL - Traceback:
Main.Manga.Bu.Run - CRITICAL - Traceback (most recent call last):
Main.Manga.Bu.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
Main.Manga.Bu.Run - CRITICAL -     self._go()
Main.Manga.Bu.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/Run.py", line 14, in _go
Main.Manga.Bu.Run - CRITICAL -     runner.go()
Main.Manga.Bu.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/MonitorRun.py", line 74, in go
Main.Manga.Bu.Run - CRITICAL -     lists = self.getListNames()
Main.Manga.Bu.Run - CRITICAL -   File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/MonitorRun.py", line 95, in getListNames
Main.Manga.Bu.Run - CRITICAL -     listList = add_seriesSegment.find_previous_sibling("p", class_="text")
Main.Manga.Bu.Run - CRITICAL - AttributeError: 'NoneType' object has no attribute 'find_previous_sibling'
Main.Manga.Bu.Run - CRITICAL - 
Main.Manga.Bu.Run - INFO - BuMon finished.

Job "callMod (trigger: interval[1:00:00], next run at: 2018-01-14 14:28:47 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "mainScrape.py", line 66, in callMod
    instance.go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/RunBase.py", line 98, in go
    self._go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/Run.py", line 14, in _go
    runner.go()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/MonitorRun.py", line 74, in go
    lists = self.getListNames()
  File "/home/samishii/Downloads/MangaCMS/MangaCMS/ScrapePlugins/M/BuMonitor/MonitorRun.py", line 95, in getListNames
    listList = add_seriesSegment.find_previous_sibling("p", class_="text")
AttributeError: 'NoneType' object has no attribute 'find_previous_sibling'

```

I can't trace back the code to even see where this type is from, otherwise i'd try to troubleshoot. But couldn't find it. Anyways, didn't know if this was an issue with the software, or my setup.

Thanks.

**Comment by fake-name** [comment]
This particular error is the MangaUpdates scraper complaining about not being able to find your reading list(s). 

If you don't care about having locally cached reading-lists, you can just ignore the error completely. It'll be harmless.

**Comment by samishii23** [comment]
Ah. Thanks for that info!

**Comment by fake-name** [comment]
I'm going to close this. Feel free to reopen if you have more issues.
